# frozen_string_literal: true
source "https://rubygems.org"


gem "sinatra"
gem "sinatra-contrib"
gem "actionmailer"

group :development do 
  gem "pry"
  gem "logger"
  gem "thor"
  gem "racksh"
  gem "sinatra-cross_origin"
end
